#!/usr/bin/env python3

import sys
import os
import traceback
import CRL
import helpers
helpers.loadUserSettings()
from   helpers.io import ErrorMessage, WarningMessage
from   helpers    import trace, l, u, n
import plugins
from   Hurricane  import DbU, Breakpoint
from   plugins.alpha.block.block         import Block
from   plugins.alpha.block.configuration import IoPin, GaugeConf
from   plugins.alpha.block.spares        import Spares
from   plugins.alpha.chip.configuration  import ChipConf
from   plugins.alpha.chip.chip           import Chip
from   plugins.alpha.core2chip.sky130    import CoreToChip


af = CRL.AllianceFramework.get()


def scriptMain ( **kw ):
    """The mandatory function to be called by Coriolis CGT/Unicorn."""
    global af
    rvalue = True
    try:
       #helpers.setTraceLevel( 540 )
       #Breakpoint.setStopLevel( 100 )
        if 'CHECK_TOOLKIT' in os.environ:
            print( 'CHECK_TOOLKIT process\n\n\n\n\n\n\n\n' )
            checkToolkitDir   = os.environ[ 'CHECK_TOOLKIT' ]
            harnessProjectDir = checkToolkitDir + '/cells/sky130'
        else:
            print( '[ERROR] The "CHECK_TOOLKIT" environment variable has not been set.'  )
            print( '        Please check "./mk/users.d/user-CONFIG.mk".'  )
            sys.exit( 1 )
        buildChip = True
        cell, editor = plugins.kwParseMain( **kw )
        cellName = 'picorv32'
        if buildChip:
            cellName += '_harness'
        cell = af.getCell( 'picorv32', CRL.Catalog.State.Logical )
        if editor:
            editor.setCell( cell ) 
            editor.setDbuMode( DbU.StringModePhysical )
        if buildChip:
            ioPinsSpec = [ ]
            ioPadsSpec = [ (None, None, 'power_0'  , 'vccd1'      , 'vdd'    )
                         , (None, None, 'ground_0' , 'vssd1'      , 'vss'    )
                        #  , (None, None, None       , 'io_in(408)'  , 'clk'    )
                         , (None, None, None       , 'io_out(0)'   , 'trap'  )
                         , (None, None, None       , 'io_out(1)'   , 'mem_valid'  )
                         , (None, None, None       , 'io_out(2)'   , 'mem_instr'  )
                         , (None, None, None       , 'io_in(3)'   , 'mem_ready'  )

                         , (None, None, None       , 'io_out(4)'   , 'mem_addr(0)'  )
                         , (None, None, None       , 'io_out(5)'   , 'mem_addr(1)'  )
                         , (None, None, None       , 'io_out(6)'   , 'mem_addr(2)'  )
                         , (None, None, None       , 'io_out(7)'   , 'mem_addr(3)'  )
                         , (None, None, None       , 'io_out(8)'   , 'mem_addr(4)'  )
                         , (None, None, None       , 'io_out(9)'   , 'mem_addr(5)'  )
                         , (None, None, None       , 'io_out(10)'   , 'mem_addr(6)'  )
                         , (None, None, None       , 'io_out(11)'   , 'mem_addr(7)'  )
                         , (None, None, None       , 'io_out(12)'   , 'mem_addr(8)'  )
                         , (None, None, None       , 'io_out(13)'   , 'mem_addr(9)'  )
                         , (None, None, None       , 'io_out(14)'   , 'mem_addr(10)'  )
                         , (None, None, None       , 'io_out(15)'   , 'mem_addr(11)'  )
                         , (None, None, None       , 'io_out(16)'   , 'mem_addr(12)'  )
                         , (None, None, None       , 'io_out(17)'   , 'mem_addr(13)'  )
                         , (None, None, None       , 'io_out(18)'   , 'mem_addr(14)'  )
                         , (None, None, None       , 'io_out(19)'   , 'mem_addr(15)'  )
                         , (None, None, None       , 'io_out(20)'   , 'mem_addr(16)'  )
                         , (None, None, None       , 'io_out(21)'   , 'mem_addr(17)'  )
                         , (None, None, None       , 'io_out(22)'   , 'mem_addr(18)'  )
                         , (None, None, None       , 'io_out(23)'   , 'mem_addr(19)'  )
                         , (None, None, None       , 'io_out(24)'   , 'mem_addr(20)'  )
                         , (None, None, None       , 'io_out(25)'   , 'mem_addr(21)'  )
                         , (None, None, None       , 'io_out(26)'   , 'mem_addr(22)'  )
                         , (None, None, None       , 'io_out(27)'   , 'mem_addr(23)'  )
                         , (None, None, None       , 'io_out(28)'   , 'mem_addr(24)'  )
                         , (None, None, None       , 'io_out(29)'   , 'mem_addr(25)'  )
                         , (None, None, None       , 'io_out(30)'   , 'mem_addr(26)'  )
                         , (None, None, None       , 'io_out(31)'   , 'mem_addr(27)'  )
                         , (None, None, None       , 'io_out(32)'   , 'mem_addr(28)'  )
                         , (None, None, None       , 'io_out(33)'   , 'mem_addr(29)'  )
                         , (None, None, None       , 'io_out(34)'   , 'mem_addr(30)'  )
                         , (None, None, None       , 'io_out(35)'   , 'mem_addr(31)'  )

                         , (None, None, None       , 'io_out(36)'   , 'mem_wdata(0)'  )
                         , (None, None, None       , 'io_out(37)'   , 'mem_wdata(1)'  )
                         , (None, None, None       , 'io_out(38)'   , 'mem_wdata(2)'  )
                         , (None, None, None       , 'io_out(39)'   , 'mem_wdata(3)'  )
                         , (None, None, None       , 'io_out(40)'   , 'mem_wdata(4)'  )
                         , (None, None, None       , 'io_out(41)'   , 'mem_wdata(5)'  )
                         , (None, None, None       , 'io_out(42)'   , 'mem_wdata(6)'  )
                         , (None, None, None       , 'io_out(43)'   , 'mem_wdata(7)'  )
                         , (None, None, None       , 'io_out(44)'   , 'mem_wdata(8)'  )
                         , (None, None, None       , 'io_out(45)'   , 'mem_wdata(9)'  )
                         , (None, None, None       , 'io_out(46)'   , 'mem_wdata(10)'  )
                         , (None, None, None       , 'io_out(47)'   , 'mem_wdata(11)'  )
                         , (None, None, None       , 'io_out(48)'   , 'mem_wdata(12)'  )
                         , (None, None, None       , 'io_out(49)'   , 'mem_wdata(13)'  )
                         , (None, None, None       , 'io_out(50)'   , 'mem_wdata(14)'  )
                         , (None, None, None       , 'io_out(51)'   , 'mem_wdata(15)'  )
                         , (None, None, None       , 'io_out(52)'   , 'mem_wdata(16)'  )
                         , (None, None, None       , 'io_out(53)'   , 'mem_wdata(17)'  )
                         , (None, None, None       , 'io_out(54)'   , 'mem_wdata(18)'  )
                         , (None, None, None       , 'io_out(55)'   , 'mem_wdata(19)'  )
                         , (None, None, None       , 'io_out(56)'   , 'mem_wdata(20)'  )
                         , (None, None, None       , 'io_out(57)'   , 'mem_wdata(21)'  )
                         , (None, None, None       , 'io_out(58)'   , 'mem_wdata(22)'  )
                         , (None, None, None       , 'io_out(59)'   , 'mem_wdata(23)'  )
                         , (None, None, None       , 'io_out(60)'   , 'mem_wdata(24)'  )
                         , (None, None, None       , 'io_out(61)'   , 'mem_wdata(25)'  )
                         , (None, None, None       , 'io_out(62)'   , 'mem_wdata(26)'  )
                         , (None, None, None       , 'io_out(63)'   , 'mem_wdata(27)'  )
                         , (None, None, None       , 'io_out(64)'   , 'mem_wdata(28)'  )
                         , (None, None, None       , 'io_out(65)'   , 'mem_wdata(29)'  )
                         , (None, None, None       , 'io_out(66)'   , 'mem_wdata(30)'  )
                         , (None, None, None       , 'io_out(67)'   , 'mem_wdata(31)'  )

                         , (None, None, None       , 'io_out(68)'   , 'mem_wstrb(0)'  )
                         , (None, None, None       , 'io_out(69)'   , 'mem_wstrb(1)'  )
                         , (None, None, None       , 'io_out(70)'   , 'mem_wstrb(2)'  )
                         , (None, None, None       , 'io_out(71)'   , 'mem_wstrb(3)'  )

                         , (None, None, None       , 'io_in(72)'   , 'mem_rdata(0)'  )
                         , (None, None, None       , 'io_in(73)'   , 'mem_rdata(1)'  )
                         , (None, None, None       , 'io_in(74)'   , 'mem_rdata(2)'  )
                         , (None, None, None       , 'io_in(75)'   , 'mem_rdata(3)'  )
                         , (None, None, None       , 'io_in(76)'   , 'mem_rdata(4)'  )
                         , (None, None, None       , 'io_in(77)'   , 'mem_rdata(5)'  )
                         , (None, None, None       , 'io_in(78)'   , 'mem_rdata(6)'  )
                         , (None, None, None       , 'io_in(79)'   , 'mem_rdata(7)'  )
                         , (None, None, None       , 'io_in(80)'   , 'mem_rdata(8)'  )
                         , (None, None, None       , 'io_in(81)'   , 'mem_rdata(9)'  )
                         , (None, None, None       , 'io_in(82)'   , 'mem_rdata(10)'  )
                         , (None, None, None       , 'io_in(83)'   , 'mem_rdata(11)'  )
                         , (None, None, None       , 'io_in(84)'   , 'mem_rdata(12)'  )
                         , (None, None, None       , 'io_in(85)'   , 'mem_rdata(13)'  )
                         , (None, None, None       , 'io_in(86)'   , 'mem_rdata(14)'  )
                         , (None, None, None       , 'io_in(87)'   , 'mem_rdata(15)'  )
                         , (None, None, None       , 'io_in(88)'   , 'mem_rdata(16)'  )
                         , (None, None, None       , 'io_in(89)'   , 'mem_rdata(17)'  )
                         , (None, None, None       , 'io_in(90)'   , 'mem_rdata(18)'  )
                         , (None, None, None       , 'io_in(91)'   , 'mem_rdata(19)'  )
                         , (None, None, None       , 'io_in(92)'   , 'mem_rdata(20)'  )
                         , (None, None, None       , 'io_in(93)'   , 'mem_rdata(21)'  )
                         , (None, None, None       , 'io_in(94)'   , 'mem_rdata(22)'  )
                         , (None, None, None       , 'io_in(95)'   , 'mem_rdata(23)'  )
                         , (None, None, None       , 'io_in(96)'   , 'mem_rdata(24)'  )
                         , (None, None, None       , 'io_in(97)'   , 'mem_rdata(25)'  )
                         , (None, None, None       , 'io_in(98)'   , 'mem_rdata(26)'  )
                         , (None, None, None       , 'io_in(99)'   , 'mem_rdata(27)'  )
                         , (None, None, None       , 'io_in(100)'   , 'mem_rdata(28)'  )
                         , (None, None, None       , 'io_in(101)'   , 'mem_rdata(29)'  )
                         , (None, None, None       , 'io_in(102)'   , 'mem_rdata(30)'  )
                         , (None, None, None       , 'io_in(103)'   , 'mem_rdata(31)'  )

                         , (None, None, None       , 'io_out(104)'   , 'mem_la_read'  )
                         , (None, None, None       , 'io_out(105)'   , 'mem_la_write'  )

                         , (None, None, None       , 'io_out(106)'   , 'mem_la_addr(0)'  )
                         , (None, None, None       , 'io_out(107)'   , 'mem_la_addr(1)'  )
                         , (None, None, None       , 'io_out(108)'   , 'mem_la_addr(2)'  )
                         , (None, None, None       , 'io_out(109)'   , 'mem_la_addr(3)'  )
                         , (None, None, None       , 'io_out(110)'   , 'mem_la_addr(4)'  )
                         , (None, None, None       , 'io_out(111)'   , 'mem_la_addr(5)'  )
                         , (None, None, None       , 'io_out(112)'   , 'mem_la_addr(6)'  )
                         , (None, None, None       , 'io_out(113)'   , 'mem_la_addr(7)'  )
                         , (None, None, None       , 'io_out(114)'   , 'mem_la_addr(8)'  )
                         , (None, None, None       , 'io_out(115)'   , 'mem_la_addr(9)'  )
                         , (None, None, None       , 'io_out(116)'   , 'mem_la_addr(10)'  )
                         , (None, None, None       , 'io_out(117)'   , 'mem_la_addr(11)'  )
                         , (None, None, None       , 'io_out(118)'   , 'mem_la_addr(12)'  )
                         , (None, None, None       , 'io_out(119)'   , 'mem_la_addr(13)'  )
                         , (None, None, None       , 'io_out(120)'   , 'mem_la_addr(14)'  )
                         , (None, None, None       , 'io_out(121)'   , 'mem_la_addr(15)'  )
                         , (None, None, None       , 'io_out(122)'   , 'mem_la_addr(16)'  )
                         , (None, None, None       , 'io_out(123)'   , 'mem_la_addr(17)'  )
                         , (None, None, None       , 'io_out(124)'   , 'mem_la_addr(18)'  )
                         , (None, None, None       , 'io_out(125)'   , 'mem_la_addr(19)'  )
                         , (None, None, None       , 'io_out(126)'   , 'mem_la_addr(20)'  )
                         , (None, None, None       , 'io_out(127)'   , 'mem_la_addr(21)'  )
                         , (None, None, None       , 'io_out(128)'   , 'mem_la_addr(22)'  )
                         , (None, None, None       , 'io_out(129)'   , 'mem_la_addr(23)'  )
                         , (None, None, None       , 'io_out(130)'   , 'mem_la_addr(24)'  )
                         , (None, None, None       , 'io_out(131)'   , 'mem_la_addr(25)'  )
                         , (None, None, None       , 'io_out(132)'   , 'mem_la_addr(26)'  )
                         , (None, None, None       , 'io_out(133)'   , 'mem_la_addr(27)'  )
                         , (None, None, None       , 'io_out(134)'   , 'mem_la_addr(28)'  )
                         , (None, None, None       , 'io_out(135)'   , 'mem_la_addr(29)'  )
                         , (None, None, None       , 'io_out(136)'   , 'mem_la_addr(30)'  )
                         , (None, None, None       , 'io_out(137)'   , 'mem_la_addr(31)'  )

                         , (None, None, None       , 'io_out(138)'   , 'mem_la_wdata(0)'  )
                         , (None, None, None       , 'io_out(139)'   , 'mem_la_wdata(1)'  )
                         , (None, None, None       , 'io_out(140)'   , 'mem_la_wdata(2)'  )
                         , (None, None, None       , 'io_out(141)'   , 'mem_la_wdata(3)'  )
                         , (None, None, None       , 'io_out(142)'   , 'mem_la_wdata(4)'  )
                         , (None, None, None       , 'io_out(143)'   , 'mem_la_wdata(5)'  )
                         , (None, None, None       , 'io_out(144)'   , 'mem_la_wdata(6)'  )
                         , (None, None, None       , 'io_out(145)'   , 'mem_la_wdata(7)'  )
                         , (None, None, None       , 'io_out(146)'   , 'mem_la_wdata(8)'  )
                         , (None, None, None       , 'io_out(147)'   , 'mem_la_wdata(9)'  )
                         , (None, None, None       , 'io_out(148)'   , 'mem_la_wdata(10)'  )
                         , (None, None, None       , 'io_out(149)'   , 'mem_la_wdata(11)'  )
                         , (None, None, None       , 'io_out(150)'   , 'mem_la_wdata(12)'  )
                         , (None, None, None       , 'io_out(151)'   , 'mem_la_wdata(13)'  )
                         , (None, None, None       , 'io_out(152)'   , 'mem_la_wdata(14)'  )
                         , (None, None, None       , 'io_out(153)'   , 'mem_la_wdata(15)'  )
                         , (None, None, None       , 'io_out(154)'   , 'mem_la_wdata(16)'  )
                         , (None, None, None       , 'io_out(155)'   , 'mem_la_wdata(17)'  )
                         , (None, None, None       , 'io_out(156)'   , 'mem_la_wdata(18)'  )
                         , (None, None, None       , 'io_out(157)'   , 'mem_la_wdata(19)'  )
                         , (None, None, None       , 'io_out(158)'   , 'mem_la_wdata(20)'  )
                         , (None, None, None       , 'io_out(159)'   , 'mem_la_wdata(21)'  )
                         , (None, None, None       , 'io_out(160)'   , 'mem_la_wdata(22)'  )
                         , (None, None, None       , 'io_out(161)'   , 'mem_la_wdata(23)'  )
                         , (None, None, None       , 'io_out(162)'   , 'mem_la_wdata(24)'  )
                         , (None, None, None       , 'io_out(163)'   , 'mem_la_wdata(25)'  )
                         , (None, None, None       , 'io_out(164)'   , 'mem_la_wdata(26)'  )
                         , (None, None, None       , 'io_out(165)'   , 'mem_la_wdata(27)'  )
                         , (None, None, None       , 'io_out(166)'   , 'mem_la_wdata(28)'  )
                         , (None, None, None       , 'io_out(167)'   , 'mem_la_wdata(29)'  )
                         , (None, None, None       , 'io_out(168)'   , 'mem_la_wdata(30)'  )
                         , (None, None, None       , 'io_out(169)'   , 'mem_la_wdata(31)'  )

                         , (None, None, None       , 'io_out(170)'   , 'mem_la_wstrb(0)'  )
                         , (None, None, None       , 'io_out(171)'   , 'mem_la_wstrb(1)'  )
                         , (None, None, None       , 'io_out(172)'   , 'mem_la_wstrb(2)'  )
                         , (None, None, None       , 'io_out(173)'   , 'mem_la_wstrb(3)'  )

                         , (None, None, None       , 'io_out(174)'   , 'pcpi_valid'  )

                         , (None, None, None       , 'io_out(175)'   , 'pcpi_insn(0)'  )
                         , (None, None, None       , 'io_out(176)'   , 'pcpi_insn(1)'  )
                         , (None, None, None       , 'io_out(177)'   , 'pcpi_insn(2)'  )
                         , (None, None, None       , 'io_out(178)'   , 'pcpi_insn(3)'  )
                         , (None, None, None       , 'io_out(179)'   , 'pcpi_insn(4)'  )
                         , (None, None, None       , 'io_out(180)'   , 'pcpi_insn(5)'  )
                         , (None, None, None       , 'io_out(181)'   , 'pcpi_insn(6)'  )
                         , (None, None, None       , 'io_out(182)'   , 'pcpi_insn(7)'  )
                         , (None, None, None       , 'io_out(183)'   , 'pcpi_insn(8)'  )
                         , (None, None, None       , 'io_out(184)'   , 'pcpi_insn(9)'  )
                         , (None, None, None       , 'io_out(185)'   , 'pcpi_insn(10)'  )
                         , (None, None, None       , 'io_out(186)'   , 'pcpi_insn(11)'  )
                         , (None, None, None       , 'io_out(187)'   , 'pcpi_insn(12)'  )
                         , (None, None, None       , 'io_out(188)'   , 'pcpi_insn(13)'  )
                         , (None, None, None       , 'io_out(189)'   , 'pcpi_insn(14)'  )
                         , (None, None, None       , 'io_out(190)'   , 'pcpi_insn(15)'  )
                         , (None, None, None       , 'io_out(191)'   , 'pcpi_insn(16)'  )
                         , (None, None, None       , 'io_out(192)'   , 'pcpi_insn(17)'  )
                         , (None, None, None       , 'io_out(193)'   , 'pcpi_insn(18)'  )
                         , (None, None, None       , 'io_out(194)'   , 'pcpi_insn(19)'  )
                         , (None, None, None       , 'io_out(195)'   , 'pcpi_insn(20)'  )
                         , (None, None, None       , 'io_out(196)'   , 'pcpi_insn(21)'  )
                         , (None, None, None       , 'io_out(197)'   , 'pcpi_insn(22)'  )
                         , (None, None, None       , 'io_out(198)'   , 'pcpi_insn(23)'  )
                         , (None, None, None       , 'io_out(199)'   , 'pcpi_insn(24)'  )
                         , (None, None, None       , 'io_out(200)'   , 'pcpi_insn(25)'  )
                         , (None, None, None       , 'io_out(201)'   , 'pcpi_insn(26)'  )
                         , (None, None, None       , 'io_out(202)'   , 'pcpi_insn(27)'  )
                         , (None, None, None       , 'io_out(203)'   , 'pcpi_insn(28)'  )
                         , (None, None, None       , 'io_out(204)'   , 'pcpi_insn(29)'  )
                         , (None, None, None       , 'io_out(205)'   , 'pcpi_insn(30)'  )
                         , (None, None, None       , 'io_out(206)'   , 'pcpi_insn(31)'  )

                         , (None, None, None       , 'io_out(207)'   , 'pcpi_rs1(0)'  )
                         , (None, None, None       , 'io_out(208)'   , 'pcpi_rs1(1)'  )
                         , (None, None, None       , 'io_out(209)'   , 'pcpi_rs1(2)'  )
                         , (None, None, None       , 'io_out(210)'   , 'pcpi_rs1(3)'  )
                         , (None, None, None       , 'io_out(211)'   , 'pcpi_rs1(4)'  )
                         , (None, None, None       , 'io_out(212)'   , 'pcpi_rs1(5)'  )
                         , (None, None, None       , 'io_out(213)'   , 'pcpi_rs1(6)'  )
                         , (None, None, None       , 'io_out(214)'   , 'pcpi_rs1(7)'  )
                         , (None, None, None       , 'io_out(215)'   , 'pcpi_rs1(8)'  )
                         , (None, None, None       , 'io_out(216)'   , 'pcpi_rs1(9)'  )
                         , (None, None, None       , 'io_out(217)'   , 'pcpi_rs1(10)'  )
                         , (None, None, None       , 'io_out(218)'   , 'pcpi_rs1(11)'  )
                         , (None, None, None       , 'io_out(219)'   , 'pcpi_rs1(12)'  )
                         , (None, None, None       , 'io_out(220)'   , 'pcpi_rs1(13)'  )
                         , (None, None, None       , 'io_out(221)'   , 'pcpi_rs1(14)'  )
                         , (None, None, None       , 'io_out(222)'   , 'pcpi_rs1(15)'  )
                         , (None, None, None       , 'io_out(223)'   , 'pcpi_rs1(16)'  )
                         , (None, None, None       , 'io_out(224)'   , 'pcpi_rs1(17)'  )
                         , (None, None, None       , 'io_out(225)'   , 'pcpi_rs1(18)'  )
                         , (None, None, None       , 'io_out(226)'   , 'pcpi_rs1(19)'  )
                         , (None, None, None       , 'io_out(227)'   , 'pcpi_rs1(20)'  )
                         , (None, None, None       , 'io_out(228)'   , 'pcpi_rs1(21)'  )
                         , (None, None, None       , 'io_out(229)'   , 'pcpi_rs1(22)'  )
                         , (None, None, None       , 'io_out(230)'   , 'pcpi_rs1(23)'  )
                         , (None, None, None       , 'io_out(231)'   , 'pcpi_rs1(24)'  )
                         , (None, None, None       , 'io_out(232)'   , 'pcpi_rs1(25)'  )
                         , (None, None, None       , 'io_out(233)'   , 'pcpi_rs1(26)'  )
                         , (None, None, None       , 'io_out(234)'   , 'pcpi_rs1(27)'  )
                         , (None, None, None       , 'io_out(235)'   , 'pcpi_rs1(28)'  )
                         , (None, None, None       , 'io_out(236)'   , 'pcpi_rs1(29)'  )
                         , (None, None, None       , 'io_out(237)'   , 'pcpi_rs1(30)'  )
                         , (None, None, None       , 'io_out(238)'   , 'pcpi_rs1(31)'  )

                        #  , (None, None, None       , 'io_out(239)'   , 'pcpi_rs2(0)'  )
                        #  , (None, None, None       , 'io_out(240)'   , 'pcpi_rs2(1)'  )
                        #  , (None, None, None       , 'io_out(241)'   , 'pcpi_rs2(2)'  )
                        #  , (None, None, None       , 'io_out(242)'   , 'pcpi_rs2(3)'  )
                        #  , (None, None, None       , 'io_out(243)'   , 'pcpi_rs2(4)'  )
                        #  , (None, None, None       , 'io_out(244)'   , 'pcpi_rs2(5)'  )
                        #  , (None, None, None       , 'io_out(245)'   , 'pcpi_rs2(6)'  )
                        #  , (None, None, None       , 'io_out(246)'   , 'pcpi_rs2(7)'  )
                         , (None, None, None       , 'io_out(247)'   , 'pcpi_rs2(8)'  )
                         , (None, None, None       , 'io_out(248)'   , 'pcpi_rs2(9)'  )
                         , (None, None, None       , 'io_out(249)'   , 'pcpi_rs2(10)'  )
                         , (None, None, None       , 'io_out(250)'   , 'pcpi_rs2(11)'  )
                         , (None, None, None       , 'io_out(251)'   , 'pcpi_rs2(12)'  )
                         , (None, None, None       , 'io_out(252)'   , 'pcpi_rs2(13)'  )
                         , (None, None, None       , 'io_out(253)'   , 'pcpi_rs2(14)'  )
                         , (None, None, None       , 'io_out(254)'   , 'pcpi_rs2(15)'  )
                         , (None, None, None       , 'io_out(255)'   , 'pcpi_rs2(16)'  )
                         , (None, None, None       , 'io_out(256)'   , 'pcpi_rs2(17)'  )
                         , (None, None, None       , 'io_out(257)'   , 'pcpi_rs2(18)'  )
                         , (None, None, None       , 'io_out(258)'   , 'pcpi_rs2(19)'  )
                         , (None, None, None       , 'io_out(259)'   , 'pcpi_rs2(20)'  )
                         , (None, None, None       , 'io_out(260)'   , 'pcpi_rs2(21)'  )
                         , (None, None, None       , 'io_out(261)'   , 'pcpi_rs2(22)'  )
                         , (None, None, None       , 'io_out(262)'   , 'pcpi_rs2(23)'  )
                         , (None, None, None       , 'io_out(263)'   , 'pcpi_rs2(24)'  )
                         , (None, None, None       , 'io_out(264)'   , 'pcpi_rs2(25)'  )
                         , (None, None, None       , 'io_out(265)'   , 'pcpi_rs2(26)'  )
                         , (None, None, None       , 'io_out(266)'   , 'pcpi_rs2(27)'  )
                         , (None, None, None       , 'io_out(267)'   , 'pcpi_rs2(28)'  )
                         , (None, None, None       , 'io_out(268)'   , 'pcpi_rs2(29)'  )
                         , (None, None, None       , 'io_out(269)'   , 'pcpi_rs2(30)'  )
                         , (None, None, None       , 'io_out(270)'   , 'pcpi_rs2(31)'  )

                         , (None, None, None       , 'io_in(271)'   , 'pcpi_wr'  )

                         , (None, None, None       , 'io_in(272)'   , 'pcpi_rd(0)'  )
                         , (None, None, None       , 'io_in(273)'   , 'pcpi_rd(1)'  )
                         , (None, None, None       , 'io_in(274)'   , 'pcpi_rd(2)'  )
                         , (None, None, None       , 'io_in(275)'   , 'pcpi_rd(3)'  )
                         , (None, None, None       , 'io_in(276)'   , 'pcpi_rd(4)'  )
                         , (None, None, None       , 'io_in(277)'   , 'pcpi_rd(5)'  )
                         , (None, None, None       , 'io_in(278)'   , 'pcpi_rd(6)'  )
                         , (None, None, None       , 'io_in(279)'   , 'pcpi_rd(7)'  )
                         , (None, None, None       , 'io_in(280)'   , 'pcpi_rd(8)'  )
                         , (None, None, None       , 'io_in(281)'   , 'pcpi_rd(9)'  )
                         , (None, None, None       , 'io_in(282)'   , 'pcpi_rd(10)'  )
                         , (None, None, None       , 'io_in(283)'   , 'pcpi_rd(11)'  )
                         , (None, None, None       , 'io_in(284)'   , 'pcpi_rd(12)'  )
                         , (None, None, None       , 'io_in(285)'   , 'pcpi_rd(13)'  )
                         , (None, None, None       , 'io_in(286)'   , 'pcpi_rd(14)'  )
                         , (None, None, None       , 'io_in(287)'   , 'pcpi_rd(15)'  )
                         , (None, None, None       , 'io_in(288)'   , 'pcpi_rd(16)'  )
                         , (None, None, None       , 'io_in(289)'   , 'pcpi_rd(17)'  )
                         , (None, None, None       , 'io_in(290)'   , 'pcpi_rd(18)'  )
                         , (None, None, None       , 'io_in(291)'   , 'pcpi_rd(19)'  )
                         , (None, None, None       , 'io_in(292)'   , 'pcpi_rd(20)'  )
                         , (None, None, None       , 'io_in(293)'   , 'pcpi_rd(21)'  )
                         , (None, None, None       , 'io_in(294)'   , 'pcpi_rd(22)'  )
                         , (None, None, None       , 'io_in(295)'   , 'pcpi_rd(23)'  )
                         , (None, None, None       , 'io_in(296)'   , 'pcpi_rd(24)'  )
                         , (None, None, None       , 'io_in(297)'   , 'pcpi_rd(25)'  )
                         , (None, None, None       , 'io_in(298)'   , 'pcpi_rd(26)'  )
                         , (None, None, None       , 'io_in(299)'   , 'pcpi_rd(27)'  )
                         , (None, None, None       , 'io_in(300)'   , 'pcpi_rd(28)'  )
                         , (None, None, None       , 'io_in(301)'   , 'pcpi_rd(29)'  )
                         , (None, None, None       , 'io_in(302)'   , 'pcpi_rd(30)'  )
                         , (None, None, None       , 'io_in(303)'   , 'pcpi_rd(31)'  )

                         , (None, None, None       , 'io_in(304)'   , 'pcpi_wait'  )
                         , (None, None, None       , 'io_in(305)'   , 'pcpi_ready'  )
            
                         , (None, None, None       , 'io_in(306)'   , 'irq(0)'  )
                         , (None, None, None       , 'io_in(307)'   , 'irq(1)'  )
                         , (None, None, None       , 'io_in(308)'   , 'irq(2)'  )
                         , (None, None, None       , 'io_in(309)'   , 'irq(3)'  )
                         , (None, None, None       , 'io_in(310)'   , 'irq(4)'  )
                         , (None, None, None       , 'io_in(311)'   , 'irq(5)'  )
                         , (None, None, None       , 'io_in(312)'   , 'irq(6)'  )
                         , (None, None, None       , 'io_in(313)'   , 'irq(7)'  )
                         , (None, None, None       , 'io_in(314)'   , 'irq(8)'  )
                         , (None, None, None       , 'io_in(315)'   , 'irq(9)'  )
                         , (None, None, None       , 'io_in(316)'   , 'irq(10)'  )
                         , (None, None, None       , 'io_in(317)'   , 'irq(11)'  )
                         , (None, None, None       , 'io_in(318)'   , 'irq(12)'  )
                         , (None, None, None       , 'io_in(319)'   , 'irq(13)'  )
                         , (None, None, None       , 'io_in(320)'   , 'irq(14)'  )
                         , (None, None, None       , 'io_in(321)'   , 'irq(15)'  )
                         , (None, None, None       , 'io_in(322)'   , 'irq(16)'  )
                         , (None, None, None       , 'io_in(323)'   , 'irq(17)'  )
                         , (None, None, None       , 'io_in(324)'   , 'irq(18)'  )
                         , (None, None, None       , 'io_in(325)'   , 'irq(19)'  )
                         , (None, None, None       , 'io_in(326)'   , 'irq(20)'  )
                         , (None, None, None       , 'io_in(327)'   , 'irq(21)'  )
                         , (None, None, None       , 'io_in(328)'   , 'irq(22)'  )
                         , (None, None, None       , 'io_in(329)'   , 'irq(23)'  )
                         , (None, None, None       , 'io_in(330)'   , 'irq(24)'  )
                         , (None, None, None       , 'io_in(331)'   , 'irq(25)'  )
                         , (None, None, None       , 'io_in(332)'   , 'irq(26)'  )
                         , (None, None, None       , 'io_in(333)'   , 'irq(27)'  )
                         , (None, None, None       , 'io_in(334)'   , 'irq(28)'  )
                         , (None, None, None       , 'io_in(335)'   , 'irq(29)'  )
                         , (None, None, None       , 'io_in(336)'   , 'irq(30)'  )
                         , (None, None, None       , 'io_in(337)'   , 'irq(31)'  )

                         , (None, None, None       , 'io_out(338)'   , 'eoi(0)'  )
                         , (None, None, None       , 'io_out(339)'   , 'eoi(1)'  )
                         , (None, None, None       , 'io_out(340)'   , 'eoi(2)'  )
                         , (None, None, None       , 'io_out(341)'   , 'eoi(3)'  )
                         , (None, None, None       , 'io_out(342)'   , 'eoi(4)'  )
                         , (None, None, None       , 'io_out(343)'   , 'eoi(5)'  )
                         , (None, None, None       , 'io_out(344)'   , 'eoi(6)'  )
                         , (None, None, None       , 'io_out(345)'   , 'eoi(7)'  )
                         , (None, None, None       , 'io_out(346)'   , 'eoi(8)'  )
                         , (None, None, None       , 'io_out(347)'   , 'eoi(9)'  )
                         , (None, None, None       , 'io_out(348)'   , 'eoi(10)'  )
                         , (None, None, None       , 'io_out(349)'   , 'eoi(11)'  )
                         , (None, None, None       , 'io_out(350)'   , 'eoi(12)'  )
                         , (None, None, None       , 'io_out(351)'   , 'eoi(13)'  )
                         , (None, None, None       , 'io_out(352)'   , 'eoi(14)'  )
                         , (None, None, None       , 'io_out(353)'   , 'eoi(15)'  )
                         , (None, None, None       , 'io_out(354)'   , 'eoi(16)'  )
                         , (None, None, None       , 'io_out(355)'   , 'eoi(17)'  )
                         , (None, None, None       , 'io_out(356)'   , 'eoi(18)'  )
                         , (None, None, None       , 'io_out(357)'   , 'eoi(19)'  )
                         , (None, None, None       , 'io_out(358)'   , 'eoi(20)'  )
                         , (None, None, None       , 'io_out(359)'   , 'eoi(21)'  )
                         , (None, None, None       , 'io_out(360)'   , 'eoi(22)'  )
                         , (None, None, None       , 'io_out(361)'   , 'eoi(23)'  )
                         , (None, None, None       , 'io_out(362)'   , 'eoi(24)'  )
                         , (None, None, None       , 'io_out(363)'   , 'eoi(25)'  )
                         , (None, None, None       , 'io_out(364)'   , 'eoi(26)'  )
                         , (None, None, None       , 'io_out(365)'   , 'eoi(27)'  )
                         , (None, None, None       , 'io_out(366)'   , 'eoi(28)'  )
                         , (None, None, None       , 'io_out(367)'   , 'eoi(29)'  )
                         , (None, None, None       , 'io_out(368)'   , 'eoi(30)'  )
                         , (None, None, None       , 'io_out(369)'   , 'eoi(31)'  )

                         , (None, None, None       , 'io_out(370)'   , 'trace_valid'  )

                         , (None, None, None       , 'io_out(371)'   , 'trace_data(0)'  )
                         , (None, None, None       , 'io_out(372)'   , 'trace_data(1)'  )
                         , (None, None, None       , 'io_out(373)'   , 'trace_data(2)'  )
                         , (None, None, None       , 'io_out(374)'   , 'trace_data(3)'  )
                         , (None, None, None       , 'io_out(375)'   , 'trace_data(4)'  )
                         , (None, None, None       , 'io_out(376)'   , 'trace_data(5)'  )
                         , (None, None, None       , 'io_out(377)'   , 'trace_data(6)'  )
                         , (None, None, None       , 'io_out(378)'   , 'trace_data(7)'  )
                         , (None, None, None       , 'io_out(379)'   , 'trace_data(8)'  )
                         , (None, None, None       , 'io_out(380)'   , 'trace_data(9)'  )
                         , (None, None, None       , 'io_out(381)'   , 'trace_data(10)'  )
                         , (None, None, None       , 'io_out(382)'   , 'trace_data(11)'  )
                         , (None, None, None       , 'io_out(383)'   , 'trace_data(12)'  )
                         , (None, None, None       , 'io_out(384)'   , 'trace_data(13)'  )
                         , (None, None, None       , 'io_out(385)'   , 'trace_data(14)'  )
                         , (None, None, None       , 'io_out(386)'   , 'trace_data(15)'  )
                         , (None, None, None       , 'io_out(387)'   , 'trace_data(16)'  )
                         , (None, None, None       , 'io_out(388)'   , 'trace_data(17)'  )
                         , (None, None, None       , 'io_out(389)'   , 'trace_data(18)'  )
                         , (None, None, None       , 'io_out(390)'   , 'trace_data(19)'  )
                         , (None, None, None       , 'io_out(391)'   , 'trace_data(20)'  )
                         , (None, None, None       , 'io_out(392)'   , 'trace_data(21)'  )
                         , (None, None, None       , 'io_out(393)'   , 'trace_data(22)'  )
                         , (None, None, None       , 'io_out(394)'   , 'trace_data(23)'  )
                         , (None, None, None       , 'io_out(395)'   , 'trace_data(24)'  )
                         , (None, None, None       , 'io_out(396)'   , 'trace_data(25)'  )
                         , (None, None, None       , 'io_out(397)'   , 'trace_data(26)'  )
                         , (None, None, None       , 'io_out(398)'   , 'trace_data(27)'  )
                         , (None, None, None       , 'io_out(399)'   , 'trace_data(28)'  )
                         , (None, None, None       , 'io_out(400)'   , 'trace_data(29)'  )
                         , (None, None, None       , 'io_out(401)'   , 'trace_data(30)'  )
                         , (None, None, None       , 'io_out(402)'   , 'trace_data(31)'  )
                         , (None, None, None       , 'io_out(403)'   , 'trace_data(32)'  )
                         , (None, None, None       , 'io_out(404)'   , 'trace_data(33)'  )
                         , (None, None, None       , 'io_out(405)'   , 'trace_data(34)'  )
                         , (None, None, None       , 'io_out(406)'   , 'trace_data(35)'  )

                         , (None, None, None       , 'io_in(407)'  , 'resetn'  )
                         ]
        else:
            m1pitch    = u(0.46)
            m2pitch    = u(0.51)
            ioPadsSpec = [ ]
            ioPinsSpec = [ (IoPin.WEST |IoPin.A_BEGIN, 'mem_addr({})'       , 10*m1pitch, 10*m1pitch, 32)
                         , (IoPin.WEST |IoPin.A_BEGIN, 'mem_wdata({})'      , 30*m1pitch, 10*m1pitch, 32)
                         , (IoPin.WEST |IoPin.A_BEGIN, 'mem_wstrb({})'      , 50*m1pitch, 10*m1pitch, 4 )
                         , (IoPin.WEST |IoPin.A_BEGIN, 'mem_rdata({})'      , 55*m1pitch, 10*m1pitch, 32)

                         , (IoPin.EAST |IoPin.A_BEGIN, 'mem_la_read'        , 10*m1pitch, 0         , 1 )
                         , (IoPin.EAST |IoPin.A_BEGIN, 'mem_la_write'       , 15*m1pitch, 0         , 1 )
                         , (IoPin.EAST |IoPin.A_BEGIN, 'mem_la_addr({})'    , 20*m1pitch, 10*m1pitch, 32)
                         , (IoPin.EAST |IoPin.A_BEGIN, 'mem_la_wdata({})'   , 25*m1pitch, 10*m1pitch, 32)
                         , (IoPin.EAST |IoPin.A_BEGIN, 'mem_la_wstrb({})'   , 30*m1pitch, 10*m1pitch, 4 )

                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_valid'         , 30*m1pitch, 0         , 1 )
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_insn({})'      , 35*m1pitch, 10*m1pitch, 32)
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_rs1({})'       , 40*m1pitch, 10*m1pitch, 32)
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_rs2({})'       , 45*m1pitch, 10*m1pitch, 32)
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_wr'            , 50*m1pitch, 0         , 1 )
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_rd({})'        , 55*m1pitch, 10*m1pitch, 32)
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_wait'          , 60*m1pitch, 0         , 1 )
                         , (IoPin.WEST |IoPin.A_BEGIN, 'pcpi_ready'         , 65*m1pitch, 0         , 1 )

                         , (IoPin.SOUTH |IoPin.A_BEGIN, 'irq({})'           , 10*m1pitch, 10*m1pitch, 32)
                         , (IoPin.SOUTH |IoPin.A_BEGIN, 'eoi({})'           , 15*m1pitch, 10*m1pitch, 32)

                         , (IoPin.SOUTH |IoPin.A_BEGIN, 'trace_valid'       , 20*m1pitch, 0         , 1 )
                         , (IoPin.SOUTH |IoPin.A_BEGIN, 'trace_data({})'    , 25*m1pitch, 10*m1pitch, 36)
                         
                         , (IoPin.NORTH|IoPin.A_BEGIN, 'clk'                , 100*m2pitch,       0 ,  1)
                         , (IoPin.NORTH|IoPin.A_BEGIN, 'trap'               , 110*m2pitch,       0 ,  1)
                         , (IoPin.NORTH|IoPin.A_BEGIN, 'mem_valid'          , 120*m2pitch,       0 ,  1)
                         , (IoPin.NORTH|IoPin.A_BEGIN, 'mem_instr'          , 130*m2pitch,       0 ,  1)
                         , (IoPin.NORTH|IoPin.A_BEGIN, 'mem_ready'          , 140*m2pitch,       0 ,  1)
                         , (IoPin.NORTH|IoPin.A_BEGIN, 'resetn'             , 150*m2pitch,       0 ,  1)
                         ]
        conf = ChipConf( cell, ioPins=ioPinsSpec, ioPads=ioPadsSpec ) 
       #conf.cfg.etesian.bloat               = 'Flexlib'
        conf.cfg.etesian.uniformDensity      = True
        conf.cfg.etesian.aspectRatio         = 1.0
       # etesian.spaceMargin is ignored if the coreSize is directly set.
        conf.cfg.etesian.spaceMargin         = 0.02
        conf.cfg.anabatic.searchHalo         = 2
        conf.cfg.anabatic.globalIterations   = 20
        conf.cfg.anabatic.topRoutingLayer    = 'm4'
        conf.cfg.katana.hTracksReservedLocal = 6
        conf.cfg.katana.vTracksReservedLocal = 3
        conf.cfg.katana.hTracksReservedMin   = 3
        conf.cfg.katana.vTracksReservedMin   = 1
        conf.cfg.katana.trackFill            = 0
        conf.cfg.katana.runRealignStage      = True
        conf.cfg.katana.dumpMeasures         = True
        conf.cfg.block.spareSide             = u(7*12)
        conf.cfg.chip.minPadSpacing          = u(1.46)
        conf.cfg.chip.supplyRailWidth        = u(20.0)
        conf.cfg.chip.supplyRailPitch        = u(40.0)
        if buildChip:
            conf.cfg.harness.path            = harnessProjectDir + '/user_project_wrapper.def'
        conf.editor              = editor
        conf.useSpares           = True
        conf.useClockTree        = True
        conf.useHFNS             = True
        conf.bColumns            = 2
        conf.bRows               = 2
        conf.chipName            = 'chip'
        conf.coreSize            = ( u( 27*12.0), u( 27*12.0) )
        conf.chipSize            = ( u(  2020.0), u(  2060.0) )
        if buildChip:
            conf.useHTree( 'io_in_from_pad(0)', Spares.HEAVY_LEAF_LOAD )
            conf.useHTree( 'io_in_from_pad(28)' )
        else:
            conf.useHTree( 'clk', Spares.HEAVY_LEAF_LOAD )
            conf.useHTree( 'resetn' )
        #conf.useHTree( 'core.subckt_0_cpu.abc_11829_new_n340' )
        if buildChip:
            arlet6502ToChip = CoreToChip( conf )
            arlet6502ToChip.buildChip()
            if editor:
                editor.setCell( conf.chip )
            chipBuilder = Chip( conf )
            chipBuilder.doChipFloorplan()
            rvalue = chipBuilder.doPnR()
            chipBuilder.save()
        else:
            blockBuilder = Block( conf )
            rvalue = blockBuilder.doPnR()
            blockBuilder.save()
    except Exception as e:
        helpers.io.catch( e )
        rvalue = False
    sys.stdout.flush()
    sys.stderr.flush()
    return rvalue


if __name__ == '__main__':
    rvalue = scriptMain()
    shellRValue = 0 if rvalue else 1
    sys.exit( shellRValue )


# TO DO
# core d'abord pour resoudre l'erreur avec clk !
# il faut jouer avec les taille de plow, core et chip.